[book]
title = "Nintendo File Formats"
description = "Documentation for file formats seen in Nintendo games"
authors = ["Yannik Marchand"]
language = "en"

[build]
create-missing = false

[output.html]
additional-css = ["theme/style.css"]
git-repository-url = "https://github.com/kinnay/Nintendo-File-Formats"

[output.html.print]
enable = false

[output.html.fold]
enable = true